# =============================================================================
#  MES Frontend - Windows one-click Nginx launcher (implementation)
#  ASCII-only on purpose: Windows PowerShell 5.1 reads .ps1 as ANSI without a BOM,
#  so Chinese text here could be mangled and break execution.
#  Chinese documentation lives in README.md section 7.2.
#
#  Steps:
#    1. locate nginx.exe        (arg 1  >  $env:NGINX_HOME  >  PATH  >  common dirs)
#    2. generate deploy\nginx.windows.gen.conf:
#         - take events{} / http{} wrapper (standalone runnable config)
#         - include conf/mime.types from the nginx directory
#         - include deploy\nginx.conf.example, with the documented Linux doc path
#           "root  /opt/mes/frontend/dist;" replaced by the real local dist path
#    3. nginx -t -c <generated>   (must pass)
#    4. start nginx (or reload when already running)
#
#  Usage:
#    deploy\start-nginx.bat
#    deploy\start-nginx.bat D:\nginx-1.25.4
# =============================================================================

$ErrorActionPreference = 'Stop'

function Write-Mes([string]$msg) { Write-Host "[MES] $msg" }
function Fail([string]$msg) { Write-Host "[MES][ERROR] $msg"; exit 1 }

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$frontendDir = (Resolve-Path (Join-Path $scriptDir '..')).Path
Write-Mes "frontend directory : $frontendDir"

# ---------------------------------------------------------------------------
# 0) dist must exist (build first)
# ---------------------------------------------------------------------------
$distDir = Join-Path $frontendDir 'dist'
$distIndex = Join-Path $distDir 'index.html'
if (-not (Test-Path $distIndex)) {
    Fail "dist\index.html not found. Run 'npm ci' and 'npm run build' in $frontendDir first."
}

# ---------------------------------------------------------------------------
# 1) locate nginx.exe
# ---------------------------------------------------------------------------
$nginxDir = $null
if ($args.Count -ge 1 -and $args[0]) { $nginxDir = $args[0] }
elseif ($env:NGINX_HOME) { $nginxDir = $env:NGINX_HOME }
else {
    $cmd = Get-Command nginx.exe -ErrorAction SilentlyContinue
    if ($cmd) { $nginxDir = Split-Path -Parent $cmd.Source }
}
if (-not $nginxDir) {
    foreach ($cand in @('C:\nginx', 'C:\nginx-1.25.4', 'C:\nginx-1.24.0', 'D:\nginx', 'D:\nginx-1.25.4', (Join-Path $env:USERPROFILE 'nginx'))) {
        if (Test-Path (Join-Path $cand 'nginx.exe')) { $nginxDir = $cand; break }
    }
}
if (-not $nginxDir) {
    Write-Host ""
    Fail @"
nginx.exe not found.
  Download "nginx/Windows" from https://nginx.org/en/download.html, unzip it, then run:
      deploy\start-nginx.bat <nginx_dir>
  Example:
      deploy\start-nginx.bat D:\nginx-1.25.4
"@
}
$nginxDir = (Resolve-Path $nginxDir).Path
$nginxExe = Join-Path $nginxDir 'nginx.exe'
if (-not (Test-Path $nginxExe)) { Fail "$nginxExe not found." }
Write-Mes "nginx directory    : $nginxDir"

# ---------------------------------------------------------------------------
# 2) generate standalone config from the example
# ---------------------------------------------------------------------------
$examplePath = Join-Path $scriptDir 'nginx.conf.example'
if (-not (Test-Path $examplePath)) { Fail "$examplePath not found." }

$distFwd = $distDir.Replace('\', '/')
$mimeFwd = (Join-Path $nginxDir 'conf\mime.types').Replace('\', '/')

$example = Get-Content -Path $examplePath -Raw -Encoding UTF8
$patched = $example.Replace('root  /opt/mes/frontend/dist;', "root  $distFwd;")
$patchedCount = ([regex]::Matches($example, [regex]::Escape('root  /opt/mes/frontend/dist;'))).Count
if ($patchedCount -eq 0) {
    Write-Mes "WARN: no 'root  /opt/mes/frontend/dist;' occurrence found; config kept as-is."
}

$genPath = Join-Path $scriptDir 'nginx.windows.gen.conf'
$gen = @"
# =============================================================================
# AUTO-GENERATED by deploy\start-nginx.ps1 - DO NOT EDIT, DO NOT COMMIT
# Source : deploy\nginx.conf.example (server block below, root path re-pointed)
# dist   : $distFwd
# =============================================================================
events { worker_connections 1024; }

http {
    include       "$mimeFwd";
    default_type  application/octet-stream;
    sendfile      on;
    access_log    logs/mes-frontend.access.log;
    error_log     logs/mes-frontend.error.log warn;

$patched
}
"@
Set-Content -Path $genPath -Value $gen -Encoding UTF8
Write-Mes "generated config   : $genPath"

# ---------------------------------------------------------------------------
# 3) syntax check
# ---------------------------------------------------------------------------
& $nginxExe -p "$nginxDir" -t -c "$genPath"
if ($LASTEXITCODE -ne 0) { Fail "nginx config test failed (see message above)." }
Write-Mes "config test        : OK"

# ---------------------------------------------------------------------------
# 4) start or reload
# ---------------------------------------------------------------------------
$running = Get-Process -Name nginx -ErrorAction SilentlyContinue
if ($running) {
    Write-Mes "nginx is running    : reloading configuration"
    & $nginxExe -p "$nginxDir" -s reload
} else {
    Write-Mes "starting nginx ..."
    Start-Process -FilePath $nginxExe -ArgumentList @('-p', $nginxDir, '-c', $genPath) -WindowStyle Hidden
}

Write-Host ""
Write-Mes "done. Checklist:"
Write-Host "       1. backend health : curl http://127.0.0.1:3000/api/health"
Write-Host "       2. open in browser: http://localhost/            (login page)"
Write-Host "       3. refresh a sub route, e.g. /equipment/list - must NOT return 404"
Write-Host "       4. port 80 occupied? edit 'listen 80;' in deploy\nginx.conf.example and re-run"
Write-Host "       5. stop nginx     : `"$nginxExe`" -p `"$nginxDir`" -s stop"
Write-Host ""
exit 0
